### ISSUE TITLE
Не найден REQ_HEAD

### ISSUE THREAD

**Issue by simsaf** [Bfgeshka/vkgrab#1]
Не найдены переменные API_VER, PERMISSIONS и REQ_HEAD. Если насчет первых двух я просто поставил верхний регистр в config.h, то последнюю найти не смог. Или я что-то делаю не так? Или апи уже не актуален?

//предыдущий issue был удален или просто не сохранился?

**Comment by Bfgeshka** [comment]
> предыдущий issue был удален или просто не сохранился?

Видишь же, что это #1

Про саму проблему не понял - где не найдены?

**Comment by Bfgeshka** [comment]
Понял, о чём это. Скорее всего недопушил изменения в config.h

Позже сегодня разберусь.
